Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	= []

CPPPATH = [cwd + '/v2.0', cwd + '/v2.0/fmt']

group = DefineGroup('MAVLINK', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
