import os
from building import *

LIBS = [
    # 'cm_backtrace',
    'mavlink',
    # 'dronecan',
]

cwd = GetCurrentDir()
objs = []
# list = os.listdir(cwd)

for d in LIBS:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
    else:
        print('Error: can not find SConscript in ' + path)
        exit(0)

Return('objs')
